export const FETCH_DANH_SACH_SV = "FETCH_DANH_SACH_SV";
export const THEM_SINH_VIEN = "THEM_SINH_VIEN";
export const XOA_SINH_VIEN = "XOA_SINH_VIEN";
export const SUA_SINH_VIEN = "SUA_SINH_VIEN";
export const CAP_NHAT_SINH_VIEN = "CAP_NHAT_SINH_VIEN";
